version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $HOST_IP_ADDR # eg: HOST_IP_ADDR=$(ipconfig getifaddr en0) docker-compose up
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "dev.betting:5:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  provider:
    image: tsgtechtest/provider:1.0.0
    ports:
      - "8181:8181"
      - "8282:8282"

  producer:
    build: producer/
    environment:
      HOST_IP_ADDR: $HOST_IP_ADDR
      HOST_IP_PORT: 9092
      PROVIDER_IP: provider
      PROVIDER_PORT: 8282
    ports:
      - "8383:8383"
    depends_on:
      - kafka
      - provider
      - zookeeper

  consumer:
    network_mode: "host"
    build: consumer/
    environment:
      SPRING_KAFKA_LISTENER_MISSING_TOPICS_FATAL: "false"
    expose:
      - "8484-8498"
    depends_on:
      - producer
      - zookeeper
      - kafka
      - mongo